package ua.com.flangex.model;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum Country {
    AALAND_ISLANDS("Aaland Islands"),
    AFGHANISTAN("Afghanistan"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    AMERICAN_SAMOA("American Samoa"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANGUILLA("Anguilla"),
    ANTARCTICA("Antarctica"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    ARUBA("Aruba"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BERMUDA("Bermuda"),
    BHUTAN("Bhutan"),
    BOLIVIA("Boliva"),
    BOSNIA_AND_HERZEGOWINA("Bosnia and Herzegowina"),
    BOTSWANA("Botswana"),
    BOUVET_ISLAND("Bouvet Island"),
    BRAZIL("Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("Brunei Darussalam"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    CAPE_VERDE("Cape Verde"),
    CAYMAN_ISLANDS("Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    CHRISTMAS_ISLAND("Christmas Island"),
    COCOS_KEELING_ISLANDS("Cocos Keeling Ilands"),
    COLOMBIA("Colombia"),
    COMOROS("Comoros"),
    CONGO("Congo"),
    COOK_ISLANDS("Cook Islands"),
    COSTA_RICA("Costa Rica"),
    COTE_DIVOIRE("Cote D'Ivoire"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    CYPRUS("Cyprus"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    EAST_TIMOR("East Timor"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    EL_SALVADOR("El Salvador"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    ERITREA("Eritera"),
    ESTONIA("Estonia"),
    ETHIOPIA("Ethiopia"),
    FALKLAND_ISLANDS("Falkland Islands"),
    FAROE_ISLANDS("Faroe Islands"),
    FIJI("Fiji"),
    FINLAND("Finland"),
    FRANCE("France"),
    FRANCE_METROPOLITAN("France Metropolitan"),
    FRENCH_GUIANA("French Guiana"),
    FRENCH_POLYNESIA("French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GHANA("Ghana"),
    GIBRALTAR("Gibraltar"),
    GREECE("Greece"),
    GREENLAND("Greenland"),
    GRENADA("Grenada"),
    GUADELOUPE("Guadeloupe"),
    GUAM("Guam"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HEARD_AND_MC_DONALD_ISLANDS("Heard and Mc'Donald Islands"),
    HONDURAS("Honduras"),
    HONG_KONG("Hong Kong"),
    HUNGARY("Hungary"),
    ICELAND("Iceland"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAN_ISLAMIC_REPUBLIC_OF("Iran, Islamic Republic of"),
    IRAQ("Iraq"),
    IRELAND("Ireland"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JORDAN("Jordan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF("Korea, Democratic People's Republic of"),
    KOREA_REPUBLIC_OF("Korea, Republic of"),
    KUWAIT("Kuwait"),
    KYRGYZSTAN("Kyrgyzstan"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("Lao, People's Democratic Republic"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBYAN_ARAB_JAMAHIRIYA("Libyan Arab Jamahiriya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MACAU("Macau"),
    MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF("Macedonia, The Former Yugoslav Republic of"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTA("Malta"),
    MARSHALL_ISLANDS("Marshall Islands"),
    MARTINIQUE("Martinique"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MAYOTTE("Mayotte"),
    MEXICO("Mexico"),
    MICRONESIA_FEDERATED_STATES_OF("Micronesia, Federated States of"),
    MOLDOVA_REPUBLIC_OF("Moldova, Republic of"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MONTSERRAT("Montserrat"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NETHERLANDS_ANTILLES("Netherlands Antilles"),
    NEW_CALEDONIA("New Caledonia"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NIUE("Niue"),
    NORFOLK_ISLAND("Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands"),
    NORWAY("Norway"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PALAU("Palau"),
    PANAMA("Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    PITCAIRN("Pitcairn"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    PUERTO_RICO("Puerto Rico"),
    QATAR("Qatar"),
    REUNION("Reunion"),
    ROMANIA("Romania"),
    RUSSIAN_FEDERATION("Russian Federation"),
    RWANDA("Rawanda"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    SAUDI_ARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierral Leone"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOLOMON_ISLANDS("Solomon Islands"),
    SOMALIA("Somalia"),
    SOUTH_AFRICA("South Africa"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    ST_HELENA("St. Helena"),
    ST_PIERRE_AND_MIQUELON("St. Pierre and Miquelon"),
    SUDAN("Sudan"),
    SURINAME("Suriname"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS("Svalbard and Jan Mayen Islands"),
    SWAZILAND("Swaziland"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic"),
    TAIWAN_PROVINCE_OF_CHINA("Taiwan, Province of China"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA_UNITED_REPUBLIC_OF("Tanzania, United Republic of"),
    THAILAND("Thailand"),
    TOGO("Togo"),
    TOKELAU("Tokelau"),
    TONGA("Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURKEY("Turkey"),
    TURKMENISTAN("Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands"),
    TUVALU("Tuvalu"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    UNITED_KINGDOM("United Kingdome"),
    UNITED_STATES("Unites States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("United States Minor Outlying Islands"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistan"),
    VANUATU("Vanuatu"),
    VATICAN_CITY_STATE("Vatican City State"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    VIRGIN_ISLANDS_BRITISH("Virgin Islands, British"),
    VIRGIN_ISLANDS_US("Virgin Islands, U.S."),
    WALLIS_AND_FUTUNA_ISLANDS("Wallis and Futuna Islands"),
    WESTERN_SAHARA("Western Sahara"),
    YEMEN("Yemen"),
    YUGOSLAVIA("Yugoslavia"),
    ZAIRE("Zaire"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe");

    private String countryName;

    Country(String countryName) {
        this.countryName = countryName;
    }

    public String getCountryName() {
        return countryName;
    }

    public static List<String> getCountries(){
        return Stream
                .of(Country.values())
                .map(Country::getCountryName)
                .collect(Collectors.toList());
    }
}
