INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description) VALUES ('Eugene', 'Deyneka','admin@gmail.com', 'ROLE_ADMIN', 'admin', 'admin', 23, 'Kiev', 'Ukraine', 'Male', 'London is a capital of Great Britain!');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description) VALUES ('Eugene', 'Deyneka','user@gmail.com', 'ROLE_USER', 'user', 'user', 23, 'Kiev', 'Ukraine', 'Male', 'London is a capital of Great Britain!');

INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Katerine', '', 'Katerine@gmail.com', 'ROLE_USER', 'vnXPWtms', 'vnXPWtms', 93, '', 'Cambodia', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Katherina', '', 'Katherina@rambler.ru', 'ROLE_USER', 'hXzXgmTJ', 'hXzXgmTJ', 117, '', 'British Indian Ocean Territory', 'Female', 'London is a capital of Great Britain!', '', '', '', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Hester', '', 'Hester@rambler.ru', 'ROLE_USER', 'KJLkhtpP', 'KJLkhtpP', 117, '', 'Northern Mariana Islands', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Chadwick', '', 'Chadwick@mail.ru', 'ROLE_USER', 'ZZVQRvQU', 'ZZVQRvQU', 108, '', 'Gibraltar', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Toma', '', 'Toma@rambler.ru', 'ROLE_USER', 'TdllVOZj', 'TdllVOZj', 18, '', 'Switzerland', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Joslyn', '', 'Joslyn@rambler.ru', 'ROLE_USER', 'dLxLUgSp', 'dLxLUgSp', 32, '', 'Croatia', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Jerilyn', '', 'Jerilyn@gmail.com', 'ROLE_USER', 'JQstvZYe', 'JQstvZYe', 52, '', 'Tajikistan', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marvin', '', 'Marvin@rambler.ru', 'ROLE_USER', 'SUNuiUlR', 'SUNuiUlR', 101, '', 'Tajikistan', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Jerilyn', '', 'Jerilyn@ukr.net', 'ROLE_USER', 'RNanJUQR', 'RNanJUQR', 31, '', 'Monaco', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Jerilyn', '', 'Jerilyn@mail.ru', 'ROLE_USER', 'ZmwxWLcK', 'ZmwxWLcK', 87, '', 'United States', 'Female', 'London is a capital of Great Britain!', '', '', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marin', '', 'Marin@ukr.net', 'ROLE_USER', 'wuWxxkdR', 'wuWxxkdR', 57, '', 'Belarus', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Lyle', '', 'Lyle@mail.ru', 'ROLE_USER', 'JQZTXkMU', 'JQZTXkMU', 46, '', 'Comoros', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Cecil', '', 'Cecil@gmail.com', 'ROLE_USER', 'hYUMnufW', 'hYUMnufW', 55, '', 'Somalia', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Elijah', '', 'Elijah@rambler.ru', 'ROLE_USER', 'ocWiQbso', 'ocWiQbso', 14, '', 'Jersey', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Vince ', '', 'Vince @ukr.net', 'ROLE_USER', 'jskrLPem', 'jskrLPem', 91, '', 'Germany', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Lyle', '', 'Lyle@gmail.com', 'ROLE_USER', 'aqyjyVQa', 'aqyjyVQa', 62, '', 'Micronesia', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Sylvester', '', 'Sylvester@gmail.com', 'ROLE_USER', 'thlWouqu', 'thlWouqu', 58, '', 'Angola', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Gabriel', '', 'Gabriel@gmail.com', 'ROLE_USER', 'tnvxRnXn', 'tnvxRnXn', 45, '', 'New Zealand', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Consuelo', '', 'Consuelo@gmail.com', 'ROLE_USER', 'kYtyppej', 'kYtyppej', 55, '', 'Puerto Rico', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Don', '', 'Don@rambler.ru', 'ROLE_USER', 'PxYNhVUw', 'PxYNhVUw', 48, '', 'Gambia', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eric', '', 'Eric@mail.ru', 'ROLE_USER', 'VjZzqvJb', 'VjZzqvJb', 22, '', 'Ukraine', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Hyun', '', 'Hyun@rambler.ru', 'ROLE_USER', 'WmTwhook', 'WmTwhook', 10, '', 'French Guiana', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Desmond', '', 'Desmond@rambler.ru', 'ROLE_USER', 'aQUanmdO', 'aQUanmdO', 107, '', 'Australia', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Dominick', '', 'Dominick@gmail.com', 'ROLE_USER', 'fUSupucZ', 'fUSupucZ', 80, '', 'Estonia', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Hyun', '', 'Hyun@mail.ru', 'ROLE_USER', 'mSzwaRqy', 'mSzwaRqy', 77, '', 'Montserrat', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Ebonie', '', 'Ebonie@mail.ru', 'ROLE_USER', 'bzcfMOjL', 'bzcfMOjL', 76, '', 'Isle Of Man', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Christoper', '', 'Christoper@mail.ru', 'ROLE_USER', 'MmQozKNO', 'MmQozKNO', 106, '', 'Panama', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Kelsi', '', 'Kelsi@rambler.ru', 'ROLE_USER', 'sYKRLbWm', 'sYKRLbWm', 58, '', 'Cyprus', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Elijah', '', 'Elijah@ukr.net', 'ROLE_USER', 'VaaVePiS', 'VaaVePiS', 24, '', 'Tonga', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Nicolas', '', 'Nicolas@rambler.ru', 'ROLE_USER', 'mwdxzUkJ', 'mwdxzUkJ', 48, '', 'British Indian Ocean Territory', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Raquel', '', 'Raquel@rambler.ru', 'ROLE_USER', 'MOjRJnhJ', 'MOjRJnhJ', 50, '', 'Kuwait', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eldridge', '', 'Eldridge@rambler.ru', 'ROLE_USER', 'QbNoWvmx', 'QbNoWvmx', 38, '', 'American Samoa', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Cecil', '', 'Cecil@mail.ru', 'ROLE_USER', 'TKLmgomm', 'TKLmgomm', 22, '', 'Morocco', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Toshia', '', 'Toshia@gmail.com', 'ROLE_USER', 'JkLNwLnT', 'JkLNwLnT', 14, '', 'Guadeloupe', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Chantay', '', 'Chantay@mail.ru', 'ROLE_USER', 'ujXqfTkT', 'ujXqfTkT', 50, '', 'Saint Barthélemy', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Pablo', '', 'Pablo@ukr.net', 'ROLE_USER', 'hJgdbRLn', 'hJgdbRLn', 110, '', 'France', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Octavio', '', 'Octavio@ukr.net', 'ROLE_USER', 'JNlRsZOd', 'JNlRsZOd', 20, '', 'Maldives', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Katherina', '', 'Katherina@mail.ru', 'ROLE_USER', 'wkWTtmNb', 'wkWTtmNb', 77, '', 'Iran', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Desmond', '', 'Desmond@mail.ru', 'ROLE_USER', 'uPwzhrUg', 'uPwzhrUg', 74, '', 'Togo', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Carlos', '', 'Carlos@mail.ru', 'ROLE_USER', 'rbngKXyv', 'rbngKXyv', 11, '', 'Botswana', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Verla', '', 'Verla@ukr.net', 'ROLE_USER', 'moOtZmQs', 'moOtZmQs', 60, '', 'Bosnia and Herzegovina', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Isiahn', '', 'Isiahn@rambler.ru', 'ROLE_USER', 'SmyTULfk', 'SmyTULfk', 61, '', 'Jordan', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Xiomara', '', 'Xiomara@ukr.net', 'ROLE_USER', 'qYacvNKY', 'qYacvNKY', 47, '', 'Saudi Arabia', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Johnie', '', 'Johnie@gmail.com', 'ROLE_USER', 'UQVWUdLM', 'UQVWUdLM', 37, '', 'Liechtenstein', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eric', '', 'Eric@ukr.net', 'ROLE_USER', 'XzxcdSLl', 'XzxcdSLl', 42, '', 'Guinea', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Benny', '', 'Benny@mail.ru', 'ROLE_USER', 'olnzbxQr', 'olnzbxQr', 32, '', 'Egypt', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Ara', '', 'Ara@mail.ru', 'ROLE_USER', 'xykyxmpZ', 'xykyxmpZ', 90, '', 'Burkina Faso', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marica', '', 'Marica@mail.ru', 'ROLE_USER', 'jWjqrSvn', 'jWjqrSvn', 110, '', 'Chad', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Johnie', '', 'Johnie@ukr.net', 'ROLE_USER', 'pkQgoczz', 'pkQgoczz', 49, '', 'Guinea-Bissau', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Joesph', '', 'Joesph@gmail.com', 'ROLE_USER', 'UiaXxblo', 'UiaXxblo', 90, '', 'Zambia', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');

INSERT INTO native_language (id, name, user_id) VALUES ('1', 'Serbian', '3');
INSERT INTO native_language (id, name, user_id) VALUES ('2', 'Pashto', '3');
INSERT INTO native_language (id, name, user_id) VALUES ('3', 'Slovak', '3');
INSERT INTO native_language (id, name, user_id) VALUES ('4', 'Bosnian', '3');
INSERT INTO native_language (id, name, user_id) VALUES ('5', 'Czech', '3');
INSERT INTO native_language (id, name, user_id) VALUES ('6', 'Azerbaijanian', '4');
INSERT INTO native_language (id, name, user_id) VALUES ('7', 'Ukrainian', '4');
INSERT INTO native_language (id, name, user_id) VALUES ('8', 'Bihari', '4');
INSERT INTO native_language (id, name, user_id) VALUES ('9', 'Romanian', '4');
INSERT INTO native_language (id, name, user_id) VALUES ('10', 'Esperanto', '4');
INSERT INTO native_language (id, name, user_id) VALUES ('11', 'Hebrew', '5');
INSERT INTO native_language (id, name, user_id) VALUES ('12', 'Udmurt', '5');
INSERT INTO native_language (id, name, user_id) VALUES ('13', 'Navajo', '5');
INSERT INTO native_language (id, name, user_id) VALUES ('14', 'Portuguese (Brazil)', '5');
INSERT INTO native_language (id, name, user_id) VALUES ('15', 'Khmer', '5');
INSERT INTO native_language (id, name, user_id) VALUES ('16', 'Uzbek', '6');
INSERT INTO native_language (id, name, user_id) VALUES ('17', 'Latin', '6');
INSERT INTO native_language (id, name, user_id) VALUES ('18', 'Tamil', '7');
INSERT INTO native_language (id, name, user_id) VALUES ('19', 'Slavic', '7');
INSERT INTO native_language (id, name, user_id) VALUES ('20', 'Indonesian', '8');
INSERT INTO native_language (id, name, user_id) VALUES ('21', 'Kannada', '8');
INSERT INTO native_language (id, name, user_id) VALUES ('22', 'Kurdish', '9');
INSERT INTO native_language (id, name, user_id) VALUES ('23', 'Arabic', '9');
INSERT INTO native_language (id, name, user_id) VALUES ('24', 'Hindi', '9');
INSERT INTO native_language (id, name, user_id) VALUES ('25', 'Azerbaijanian', '9');
INSERT INTO native_language (id, name, user_id) VALUES ('26', 'Welsh', '10');
INSERT INTO native_language (id, name, user_id) VALUES ('27', 'Italian', '10');
INSERT INTO native_language (id, name, user_id) VALUES ('28', 'Laotian', '10');
INSERT INTO native_language (id, name, user_id) VALUES ('29', 'Hungarian', '10');
INSERT INTO native_language (id, name, user_id) VALUES ('30', 'Welsh', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('31', 'Kurdish', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('32', 'Portuguese (Brazil)', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('33', 'Swahili', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('34', 'Persian', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('35', 'Estonian', '11');
INSERT INTO native_language (id, name, user_id) VALUES ('36', 'Ainu', '12');
INSERT INTO native_language (id, name, user_id) VALUES ('37', 'Hindi', '12');
INSERT INTO native_language (id, name, user_id) VALUES ('38', 'Greek', '12');
INSERT INTO native_language (id, name, user_id) VALUES ('39', 'Bosnian', '12');
INSERT INTO native_language (id, name, user_id) VALUES ('40', 'Sinhalese', '12');
INSERT INTO native_language (id, name, user_id) VALUES ('41', 'Albanian', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('42', 'Romani', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('43', 'Irish', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('44', 'Slovak', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('45', 'Lithuanian', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('46', 'Swedish', '13');
INSERT INTO native_language (id, name, user_id) VALUES ('47', 'Javanese', '14');
INSERT INTO native_language (id, name, user_id) VALUES ('48', 'Tagalog', '14');
INSERT INTO native_language (id, name, user_id) VALUES ('49', 'Mandarin', '15');
INSERT INTO native_language (id, name, user_id) VALUES ('50', 'Spanish', '15');
INSERT INTO native_language (id, name, user_id) VALUES ('51', 'Burmese', '15');
INSERT INTO native_language (id, name, user_id) VALUES ('52', 'Latvian', '15');
INSERT INTO native_language (id, name, user_id) VALUES ('53', 'Icelandic', '15');
INSERT INTO native_language (id, name, user_id) VALUES ('54', 'Welsh', '16');
INSERT INTO native_language (id, name, user_id) VALUES ('55', 'Maltese', '16');
INSERT INTO native_language (id, name, user_id) VALUES ('56', 'Chinese Traditional', '16');
INSERT INTO native_language (id, name, user_id) VALUES ('57', 'Swedish', '16');
INSERT INTO native_language (id, name, user_id) VALUES ('58', 'Gaelic', '16');
INSERT INTO native_language (id, name, user_id) VALUES ('59', 'Swahili', '17');
INSERT INTO native_language (id, name, user_id) VALUES ('60', 'Flemish', '17');
INSERT INTO native_language (id, name, user_id) VALUES ('61', 'Bengali', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('62', 'Romani', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('63', 'Panjabi', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('64', 'Estonian', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('65', 'Haitian', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('66', 'Korean', '18');
INSERT INTO native_language (id, name, user_id) VALUES ('67', 'Urdu', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('68', 'Burmese', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('69', 'Tamil', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('70', 'Panjabi', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('71', 'Romani', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('72', 'Ossetic', '19');
INSERT INTO native_language (id, name, user_id) VALUES ('73', 'Estonian', '20');
INSERT INTO native_language (id, name, user_id) VALUES ('74', 'Swahili', '20');
INSERT INTO native_language (id, name, user_id) VALUES ('75', 'Panjabi', '20');
INSERT INTO native_language (id, name, user_id) VALUES ('76', 'Bulgarian', '21');
INSERT INTO native_language (id, name, user_id) VALUES ('77', 'Flemish', '21');
INSERT INTO native_language (id, name, user_id) VALUES ('78', 'Welsh', '21');
INSERT INTO native_language (id, name, user_id) VALUES ('79', 'Panjabi', '21');
INSERT INTO native_language (id, name, user_id) VALUES ('80', 'Dutch', '21');
INSERT INTO native_language (id, name, user_id) VALUES ('81', 'Telugu', '22');
INSERT INTO native_language (id, name, user_id) VALUES ('82', 'Pashto', '22');
INSERT INTO native_language (id, name, user_id) VALUES ('83', 'English', '22');
INSERT INTO native_language (id, name, user_id) VALUES ('84', 'Navajo', '22');
INSERT INTO native_language (id, name, user_id) VALUES ('85', 'Swedish', '22');
INSERT INTO native_language (id, name, user_id) VALUES ('86', 'Latvian', '23');
INSERT INTO native_language (id, name, user_id) VALUES ('87', 'Ainu', '23');
INSERT INTO native_language (id, name, user_id) VALUES ('88', 'Kirghiz', '23');
INSERT INTO native_language (id, name, user_id) VALUES ('89', 'Greek', '24');
INSERT INTO native_language (id, name, user_id) VALUES ('90', 'Mandarin', '24');
INSERT INTO native_language (id, name, user_id) VALUES ('91', 'Udmurt', '24');
INSERT INTO native_language (id, name, user_id) VALUES ('92', 'Welsh', '24');
INSERT INTO native_language (id, name, user_id) VALUES ('93', 'Italian', '24');
INSERT INTO native_language (id, name, user_id) VALUES ('94', 'Malay', '25');
INSERT INTO native_language (id, name, user_id) VALUES ('95', 'Icelandic', '25');
INSERT INTO native_language (id, name, user_id) VALUES ('96', 'Breton', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('97', 'Hindi', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('98', 'Bengali', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('99', 'Spanish', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('100', 'Laotian', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('101', 'Korean', '26');
INSERT INTO native_language (id, name, user_id) VALUES ('102', 'Norwegian', '27');
INSERT INTO native_language (id, name, user_id) VALUES ('103', 'Turkmen', '27');
INSERT INTO native_language (id, name, user_id) VALUES ('104', 'Mandarin', '27');
INSERT INTO native_language (id, name, user_id) VALUES ('105', 'Laotian', '27');
INSERT INTO native_language (id, name, user_id) VALUES ('106', 'Malay', '27');
INSERT INTO native_language (id, name, user_id) VALUES ('107', 'Thai', '28');
INSERT INTO native_language (id, name, user_id) VALUES ('108', 'Ainu', '28');
INSERT INTO native_language (id, name, user_id) VALUES ('109', 'Hungarian', '28');
INSERT INTO native_language (id, name, user_id) VALUES ('110', 'Ossetic', '29');
INSERT INTO native_language (id, name, user_id) VALUES ('111', 'Cantonese', '29');
INSERT INTO native_language (id, name, user_id) VALUES ('112', 'English', '29');
INSERT INTO native_language (id, name, user_id) VALUES ('113', 'Marathi', '29');
INSERT INTO native_language (id, name, user_id) VALUES ('114', 'Hawaiian', '29');
INSERT INTO native_language (id, name, user_id) VALUES ('115', 'Catalan', '30');
INSERT INTO native_language (id, name, user_id) VALUES ('116', 'Turkmen', '30');
INSERT INTO native_language (id, name, user_id) VALUES ('117', 'Macedonian', '30');
INSERT INTO native_language (id, name, user_id) VALUES ('118', 'Mongolian', '30');
INSERT INTO native_language (id, name, user_id) VALUES ('119', 'Tagalog', '31');
INSERT INTO native_language (id, name, user_id) VALUES ('120', 'Korean', '31');
INSERT INTO native_language (id, name, user_id) VALUES ('121', 'Hungarian', '31');
INSERT INTO native_language (id, name, user_id) VALUES ('122', 'Turkish', '32');
INSERT INTO native_language (id, name, user_id) VALUES ('123', 'Malay', '32');
INSERT INTO native_language (id, name, user_id) VALUES ('124', 'Vietnamese', '32');
INSERT INTO native_language (id, name, user_id) VALUES ('125', 'Udmurt', '33');
INSERT INTO native_language (id, name, user_id) VALUES ('126', 'Latvian', '33');
INSERT INTO native_language (id, name, user_id) VALUES ('127', 'Sinhalese', '33');
INSERT INTO native_language (id, name, user_id) VALUES ('128', 'Basque', '33');
INSERT INTO native_language (id, name, user_id) VALUES ('129', 'Breton', '34');
INSERT INTO native_language (id, name, user_id) VALUES ('130', 'Slovenian', '34');
INSERT INTO native_language (id, name, user_id) VALUES ('131', 'Vietnamese', '34');
INSERT INTO native_language (id, name, user_id) VALUES ('132', 'Urdu', '35');
INSERT INTO native_language (id, name, user_id) VALUES ('133', 'Irish', '35');
INSERT INTO native_language (id, name, user_id) VALUES ('134', 'Albanian', '36');
INSERT INTO native_language (id, name, user_id) VALUES ('135', 'Mongolian', '36');
INSERT INTO native_language (id, name, user_id) VALUES ('136', 'Panjabi', '36');
INSERT INTO native_language (id, name, user_id) VALUES ('137', 'Kurdish', '36');
INSERT INTO native_language (id, name, user_id) VALUES ('138', 'Yiddish', '37');
INSERT INTO native_language (id, name, user_id) VALUES ('139', 'Hawaiian', '37');
INSERT INTO native_language (id, name, user_id) VALUES ('140', 'Welsh', '37');
INSERT INTO native_language (id, name, user_id) VALUES ('141', 'Persian', '37');
INSERT INTO native_language (id, name, user_id) VALUES ('142', 'Georgian', '37');
INSERT INTO native_language (id, name, user_id) VALUES ('143', 'Georgian', '38');
INSERT INTO native_language (id, name, user_id) VALUES ('144', 'Breton', '38');
INSERT INTO native_language (id, name, user_id) VALUES ('145', 'Tamil', '38');
INSERT INTO native_language (id, name, user_id) VALUES ('146', 'Bihari', '39');
INSERT INTO native_language (id, name, user_id) VALUES ('147', 'Azerbaijanian', '39');
INSERT INTO native_language (id, name, user_id) VALUES ('148', 'Marathi', '39');
INSERT INTO native_language (id, name, user_id) VALUES ('149', 'Greek', '39');
INSERT INTO native_language (id, name, user_id) VALUES ('150', 'Khmer', '39');
INSERT INTO native_language (id, name, user_id) VALUES ('151', 'Irish', '40');
INSERT INTO native_language (id, name, user_id) VALUES ('152', 'Mandarin', '40');
INSERT INTO native_language (id, name, user_id) VALUES ('153', 'Armenian', '40');
INSERT INTO native_language (id, name, user_id) VALUES ('154', 'Telugu', '40');
INSERT INTO native_language (id, name, user_id) VALUES ('155', 'Cantonese', '40');
INSERT INTO native_language (id, name, user_id) VALUES ('156', 'Swedish', '41');
INSERT INTO native_language (id, name, user_id) VALUES ('157', 'Romanian', '41');
INSERT INTO native_language (id, name, user_id) VALUES ('158', 'Kirghiz', '42');
INSERT INTO native_language (id, name, user_id) VALUES ('159', 'Polish', '42');
INSERT INTO native_language (id, name, user_id) VALUES ('160', 'Kirghiz', '43');
INSERT INTO native_language (id, name, user_id) VALUES ('161', 'Dutch', '43');
INSERT INTO native_language (id, name, user_id) VALUES ('162', 'Danish', '43');
INSERT INTO native_language (id, name, user_id) VALUES ('163', 'Navajo', '43');
INSERT INTO native_language (id, name, user_id) VALUES ('164', 'Latin', '43');
INSERT INTO native_language (id, name, user_id) VALUES ('165', 'Haitian', '44');
INSERT INTO native_language (id, name, user_id) VALUES ('166', 'Bosnian', '44');
INSERT INTO native_language (id, name, user_id) VALUES ('167', 'Navajo', '45');
INSERT INTO native_language (id, name, user_id) VALUES ('168', 'Pashto', '45');
INSERT INTO native_language (id, name, user_id) VALUES ('169', 'Swahili', '45');
INSERT INTO native_language (id, name, user_id) VALUES ('170', 'Icelandic', '45');
INSERT INTO native_language (id, name, user_id) VALUES ('171', 'Ukrainian', '46');
INSERT INTO native_language (id, name, user_id) VALUES ('172', 'Bosnian', '46');
INSERT INTO native_language (id, name, user_id) VALUES ('173', 'Laotian', '46');
INSERT INTO native_language (id, name, user_id) VALUES ('174', 'Mongolian', '47');
INSERT INTO native_language (id, name, user_id) VALUES ('175', 'Turkmen', '47');
INSERT INTO native_language (id, name, user_id) VALUES ('176', 'Slovak', '47');
INSERT INTO native_language (id, name, user_id) VALUES ('177', 'Cantonese', '48');
INSERT INTO native_language (id, name, user_id) VALUES ('178', 'Arabic', '48');
INSERT INTO native_language (id, name, user_id) VALUES ('179', 'Bosnian', '48');
INSERT INTO native_language (id, name, user_id) VALUES ('180', 'Hebrew', '49');
INSERT INTO native_language (id, name, user_id) VALUES ('181', 'Afrikans', '49');
INSERT INTO native_language (id, name, user_id) VALUES ('182', 'Italian', '49');
INSERT INTO native_language (id, name, user_id) VALUES ('183', 'Kirghiz', '50');
INSERT INTO native_language (id, name, user_id) VALUES ('184', 'Welsh', '50');
INSERT INTO native_language (id, name, user_id) VALUES ('185', 'Italian', '50');
INSERT INTO native_language (id, name, user_id) VALUES ('186', 'Hindi', '50');

INSERT INTO native_language (id, name, user_id) VALUES ('187', 'Mongolian', '51');
INSERT INTO native_language (id, name, user_id) VALUES ('188', 'Laotian', '51');
INSERT INTO native_language (id, name, user_id) VALUES ('189', 'Hebrew', '52');
INSERT INTO native_language (id, name, user_id) VALUES ('190', 'Italian', '52');
INSERT INTO native_language (id, name, user_id) VALUES ('191', 'Icelandic', '52');

INSERT INTO practicing_language (id, name, user_id) VALUES ('1', 'Ainu', '3');
INSERT INTO practicing_language (id, name, user_id) VALUES ('2', 'Panjabi', '3');
INSERT INTO practicing_language (id, name, user_id) VALUES ('3', 'Urdu', '3');
INSERT INTO practicing_language (id, name, user_id) VALUES ('4', 'Slavic', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('5', 'Serbian', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('6', 'Norwegian', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('7', 'Mongolian', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('8', 'Javanese', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('9', 'Arabic', '4');
INSERT INTO practicing_language (id, name, user_id) VALUES ('10', 'Armenian', '5');
INSERT INTO practicing_language (id, name, user_id) VALUES ('11', 'Thai', '5');
INSERT INTO practicing_language (id, name, user_id) VALUES ('12', 'Czech', '6');
INSERT INTO practicing_language (id, name, user_id) VALUES ('13', 'Thai', '6');
INSERT INTO practicing_language (id, name, user_id) VALUES ('14', 'Tongan', '6');
INSERT INTO practicing_language (id, name, user_id) VALUES ('15', 'Kirghiz', '7');
INSERT INTO practicing_language (id, name, user_id) VALUES ('16', 'Mandarin', '7');
INSERT INTO practicing_language (id, name, user_id) VALUES ('17', 'Hebrew', '7');
INSERT INTO practicing_language (id, name, user_id) VALUES ('18', 'Hawaiian', '8');
INSERT INTO practicing_language (id, name, user_id) VALUES ('19', 'Serbian', '8');
INSERT INTO practicing_language (id, name, user_id) VALUES ('20', 'Thai', '9');
INSERT INTO practicing_language (id, name, user_id) VALUES ('21', 'Lithuanian', '9');
INSERT INTO practicing_language (id, name, user_id) VALUES ('22', 'Hindi', '9');
INSERT INTO practicing_language (id, name, user_id) VALUES ('23', 'Maltese', '10');
INSERT INTO practicing_language (id, name, user_id) VALUES ('24', 'Slovak', '10');
INSERT INTO practicing_language (id, name, user_id) VALUES ('25', 'Greek', '10');
INSERT INTO practicing_language (id, name, user_id) VALUES ('26', 'Serbian', '10');
INSERT INTO practicing_language (id, name, user_id) VALUES ('27', 'Hebrew', '10');
INSERT INTO practicing_language (id, name, user_id) VALUES ('28', 'Arabic', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('29', 'Persian', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('30', 'Haitian', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('31', 'Armenian', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('32', 'English', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('33', 'Tongan', '11');
INSERT INTO practicing_language (id, name, user_id) VALUES ('34', 'Slavic', '12');
INSERT INTO practicing_language (id, name, user_id) VALUES ('35', 'Romanian', '12');
INSERT INTO practicing_language (id, name, user_id) VALUES ('36', 'Zulu', '12');
INSERT INTO practicing_language (id, name, user_id) VALUES ('37', 'Sinhalese', '13');
INSERT INTO practicing_language (id, name, user_id) VALUES ('38', 'Arabic', '13');
INSERT INTO practicing_language (id, name, user_id) VALUES ('39', 'Latin', '13');
INSERT INTO practicing_language (id, name, user_id) VALUES ('40', 'Udmurt', '13');
INSERT INTO practicing_language (id, name, user_id) VALUES ('41', 'Ossetic', '13');
INSERT INTO practicing_language (id, name, user_id) VALUES ('42', 'Faroese', '14');
INSERT INTO practicing_language (id, name, user_id) VALUES ('43', 'Lojban', '14');
INSERT INTO practicing_language (id, name, user_id) VALUES ('44', 'Uzbek', '15');
INSERT INTO practicing_language (id, name, user_id) VALUES ('45', 'Pashto', '15');
INSERT INTO practicing_language (id, name, user_id) VALUES ('46', 'Marathi', '15');
INSERT INTO practicing_language (id, name, user_id) VALUES ('47', 'Slovenian', '16');
INSERT INTO practicing_language (id, name, user_id) VALUES ('48', 'Slavic', '16');
INSERT INTO practicing_language (id, name, user_id) VALUES ('49', 'Estonian', '16');
INSERT INTO practicing_language (id, name, user_id) VALUES ('50', 'Serbian', '16');
INSERT INTO practicing_language (id, name, user_id) VALUES ('51', 'Hawaiian', '17');
INSERT INTO practicing_language (id, name, user_id) VALUES ('52', 'Cantonese', '17');
INSERT INTO practicing_language (id, name, user_id) VALUES ('53', 'Breton', '17');
INSERT INTO practicing_language (id, name, user_id) VALUES ('54', 'Turkmen', '17');
INSERT INTO practicing_language (id, name, user_id) VALUES ('55', 'Macedonian', '17');
INSERT INTO practicing_language (id, name, user_id) VALUES ('56', 'Latin', '18');
INSERT INTO practicing_language (id, name, user_id) VALUES ('57', 'Dutch', '18');
INSERT INTO practicing_language (id, name, user_id) VALUES ('58', 'Yiddish', '18');
INSERT INTO practicing_language (id, name, user_id) VALUES ('59', 'Greek', '18');
INSERT INTO practicing_language (id, name, user_id) VALUES ('60', 'Turkish', '18');
INSERT INTO practicing_language (id, name, user_id) VALUES ('61', 'Cantonese', '19');
INSERT INTO practicing_language (id, name, user_id) VALUES ('62', 'Bengali', '19');
INSERT INTO practicing_language (id, name, user_id) VALUES ('63', 'Mongolian', '19');
INSERT INTO practicing_language (id, name, user_id) VALUES ('64', 'Czech', '20');
INSERT INTO practicing_language (id, name, user_id) VALUES ('65', 'Portuguese (Portugal)', '20');
INSERT INTO practicing_language (id, name, user_id) VALUES ('66', 'Laotian', '21');
INSERT INTO practicing_language (id, name, user_id) VALUES ('67', 'Japanese', '21');
INSERT INTO practicing_language (id, name, user_id) VALUES ('68', 'German', '22');
INSERT INTO practicing_language (id, name, user_id) VALUES ('69', 'Armenian', '22');
INSERT INTO practicing_language (id, name, user_id) VALUES ('70', 'Latvian', '22');
INSERT INTO practicing_language (id, name, user_id) VALUES ('71', 'Estonian', '22');
INSERT INTO practicing_language (id, name, user_id) VALUES ('72', 'Latin', '22');
INSERT INTO practicing_language (id, name, user_id) VALUES ('73', 'Macedonian', '23');
INSERT INTO practicing_language (id, name, user_id) VALUES ('74', 'Haitian', '23');
INSERT INTO practicing_language (id, name, user_id) VALUES ('75', 'Faroese', '23');
INSERT INTO practicing_language (id, name, user_id) VALUES ('76', 'Laotian', '23');
INSERT INTO practicing_language (id, name, user_id) VALUES ('77', 'Panjabi', '24');
INSERT INTO practicing_language (id, name, user_id) VALUES ('78', 'Myanmar', '24');
INSERT INTO practicing_language (id, name, user_id) VALUES ('79', 'Serbian', '24');
INSERT INTO practicing_language (id, name, user_id) VALUES ('80', 'Ainu', '24');
INSERT INTO practicing_language (id, name, user_id) VALUES ('81', 'Navajo', '25');
INSERT INTO practicing_language (id, name, user_id) VALUES ('82', 'Tamil', '25');
INSERT INTO practicing_language (id, name, user_id) VALUES ('83', 'Kirghiz', '26');
INSERT INTO practicing_language (id, name, user_id) VALUES ('84', 'Tamil', '26');
INSERT INTO practicing_language (id, name, user_id) VALUES ('85', 'Estonian', '26');
INSERT INTO practicing_language (id, name, user_id) VALUES ('86', 'Latvian', '26');
INSERT INTO practicing_language (id, name, user_id) VALUES ('87', 'German', '26');
INSERT INTO practicing_language (id, name, user_id) VALUES ('88', 'Tagalog', '27');
INSERT INTO practicing_language (id, name, user_id) VALUES ('89', 'Bengali', '27');
INSERT INTO practicing_language (id, name, user_id) VALUES ('90', 'Lithuanian', '27');
INSERT INTO practicing_language (id, name, user_id) VALUES ('91', 'Vietnamese', '28');
INSERT INTO practicing_language (id, name, user_id) VALUES ('92', 'Lojban', '28');
INSERT INTO practicing_language (id, name, user_id) VALUES ('93', 'Ossetic', '28');
INSERT INTO practicing_language (id, name, user_id) VALUES ('94', 'Lithuanian', '28');
INSERT INTO practicing_language (id, name, user_id) VALUES ('95', 'Sinhalese', '29');
INSERT INTO practicing_language (id, name, user_id) VALUES ('96', 'Swahili', '29');
INSERT INTO practicing_language (id, name, user_id) VALUES ('97', 'Khmer', '29');
INSERT INTO practicing_language (id, name, user_id) VALUES ('98', 'Kannada', '29');
INSERT INTO practicing_language (id, name, user_id) VALUES ('99', 'Finnish', '29');
INSERT INTO practicing_language (id, name, user_id) VALUES ('100', 'Finnish', '30');
INSERT INTO practicing_language (id, name, user_id) VALUES ('101', 'Javanese', '30');
INSERT INTO practicing_language (id, name, user_id) VALUES ('102', 'Gaelic', '30');
INSERT INTO practicing_language (id, name, user_id) VALUES ('103', 'Vietnamese', '30');
INSERT INTO practicing_language (id, name, user_id) VALUES ('104', 'Georgian', '31');
INSERT INTO practicing_language (id, name, user_id) VALUES ('105', 'Slovak', '31');
INSERT INTO practicing_language (id, name, user_id) VALUES ('106', 'Vietnamese', '32');
INSERT INTO practicing_language (id, name, user_id) VALUES ('107', 'Finnish', '32');
INSERT INTO practicing_language (id, name, user_id) VALUES ('108', 'Japanese', '32');
INSERT INTO practicing_language (id, name, user_id) VALUES ('109', 'Faroese', '33');
INSERT INTO practicing_language (id, name, user_id) VALUES ('110', 'Kurdish', '33');
INSERT INTO practicing_language (id, name, user_id) VALUES ('111', 'Croatian', '33');
INSERT INTO practicing_language (id, name, user_id) VALUES ('112', 'Polish', '34');
INSERT INTO practicing_language (id, name, user_id) VALUES ('113', 'Portuguese (Brazil)', '34');
INSERT INTO practicing_language (id, name, user_id) VALUES ('114', 'Urdu', '35');
INSERT INTO practicing_language (id, name, user_id) VALUES ('115', 'Kannada', '35');
INSERT INTO practicing_language (id, name, user_id) VALUES ('116', 'Spanish', '35');
INSERT INTO practicing_language (id, name, user_id) VALUES ('117', 'Japanese', '35');
INSERT INTO practicing_language (id, name, user_id) VALUES ('118', 'Hebrew', '35');
INSERT INTO practicing_language (id, name, user_id) VALUES ('119', 'Hebrew', '36');
INSERT INTO practicing_language (id, name, user_id) VALUES ('120', 'Lojban', '36');
INSERT INTO practicing_language (id, name, user_id) VALUES ('121', 'Spanish', '36');
INSERT INTO practicing_language (id, name, user_id) VALUES ('122', 'Laotian', '36');
INSERT INTO practicing_language (id, name, user_id) VALUES ('123', 'Laotian', '37');
INSERT INTO practicing_language (id, name, user_id) VALUES ('124', 'Polish', '37');
INSERT INTO practicing_language (id, name, user_id) VALUES ('125', 'Marathi', '37');
INSERT INTO practicing_language (id, name, user_id) VALUES ('126', 'Romanian', '37');
INSERT INTO practicing_language (id, name, user_id) VALUES ('127', 'Greek', '37');
INSERT INTO practicing_language (id, name, user_id) VALUES ('128', 'Italian', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('129', 'Myanmar', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('130', 'Slavic', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('131', 'Hebrew', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('132', 'Bihari', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('133', 'Dutch', '38');
INSERT INTO practicing_language (id, name, user_id) VALUES ('134', 'Italian', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('135', 'Icelandic', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('136', 'Uyghur', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('137', 'Irish', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('138', 'Yiddish', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('139', 'Javanese', '39');
INSERT INTO practicing_language (id, name, user_id) VALUES ('140', 'Russian', '40');
INSERT INTO practicing_language (id, name, user_id) VALUES ('141', 'Polish', '40');
INSERT INTO practicing_language (id, name, user_id) VALUES ('142', 'Latvian', '41');
INSERT INTO practicing_language (id, name, user_id) VALUES ('143', 'Korean', '41');
INSERT INTO practicing_language (id, name, user_id) VALUES ('144', 'Breton', '42');
INSERT INTO practicing_language (id, name, user_id) VALUES ('145', 'Afrikans', '42');
INSERT INTO practicing_language (id, name, user_id) VALUES ('146', 'Lojban', '42');
INSERT INTO practicing_language (id, name, user_id) VALUES ('147', 'Gaelic', '42');
INSERT INTO practicing_language (id, name, user_id) VALUES ('148', 'Slovenian', '42');
INSERT INTO practicing_language (id, name, user_id) VALUES ('149', 'Ukrainian', '43');
INSERT INTO practicing_language (id, name, user_id) VALUES ('150', 'Croatian', '43');
INSERT INTO practicing_language (id, name, user_id) VALUES ('151', 'Greek', '43');
INSERT INTO practicing_language (id, name, user_id) VALUES ('152', 'Maltese', '43');
INSERT INTO practicing_language (id, name, user_id) VALUES ('153', 'Portuguese (Brazil)', '44');
INSERT INTO practicing_language (id, name, user_id) VALUES ('154', 'Haitian', '44');
INSERT INTO practicing_language (id, name, user_id) VALUES ('155', 'Pashto', '44');
INSERT INTO practicing_language (id, name, user_id) VALUES ('156', 'Thai', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('157', 'Kurdish', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('158', 'Tibetan', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('159', 'Georgian', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('160', 'Navajo', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('161', 'Irish', '45');
INSERT INTO practicing_language (id, name, user_id) VALUES ('162', 'Romani', '46');
INSERT INTO practicing_language (id, name, user_id) VALUES ('163', 'Marathi', '46');
INSERT INTO practicing_language (id, name, user_id) VALUES ('164', 'Welsh', '46');
INSERT INTO practicing_language (id, name, user_id) VALUES ('165', 'Japanese', '46');
INSERT INTO practicing_language (id, name, user_id) VALUES ('166', 'Lojban', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('167', 'Uzbek', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('168', 'Esperanto', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('169', 'Cantonese', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('170', 'Afrikans', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('171', 'Lithuanian', '47');
INSERT INTO practicing_language (id, name, user_id) VALUES ('172', 'Hawaiian', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('173', 'Portuguese (Portugal)', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('174', 'German', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('175', 'Persian', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('176', 'Czech', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('177', 'Myanmar', '48');
INSERT INTO practicing_language (id, name, user_id) VALUES ('178', 'Latvian', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('179', 'Catalan', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('180', 'Myanmar', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('181', 'Romanian', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('182', 'Hebrew', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('183', 'Bengali', '49');
INSERT INTO practicing_language (id, name, user_id) VALUES ('184', 'Burmese', '50');
INSERT INTO practicing_language (id, name, user_id) VALUES ('185', 'Flemish', '50');
INSERT INTO practicing_language (id, name, user_id) VALUES ('186', 'Macedonian', '50');
INSERT INTO practicing_language (id, name, user_id) VALUES ('187', 'Turkish', '50');
INSERT INTO practicing_language (id, name, user_id) VALUES ('188', 'Bengali', '50');
INSERT INTO practicing_language (id, name, user_id) VALUES ('189', 'Faroese', '50');

INSERT INTO practicing_language (id, name, user_id) VALUES ('190', 'Afrikans', '51');
INSERT INTO practicing_language (id, name, user_id) VALUES ('191', 'Japanese', '51');
INSERT INTO practicing_language (id, name, user_id) VALUES ('192', 'Persian', '52');
INSERT INTO practicing_language (id, name, user_id) VALUES ('193', 'Esperanto', '52');
INSERT INTO practicing_language (id, name, user_id) VALUES ('194', 'Marathi', '52');
