INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eugene', 'Deyneka','admin@gmail.com', 'ROLE_ADMIN', 'admin', 'admin', 23, 'Kiev', 'Ukraine', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eugene', 'Deyneka','user@gmail.com', 'ROLE_USER', 'user', 'user', 23, 'Kiev', 'Ukraine', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Cecil', '', 'Cecil@mail.ru', 'ROLE_USER', 'zYzKJYJr', 'zYzKJYJr', 9, '', 'Wallis And Futuna', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Octavio', '', 'Octavio@mail.ru', 'ROLE_USER', 'ZyctRmRz', 'ZyctRmRz', 93, '', 'Sint Maarten (Dutch part)', 'Male', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Christoper', '', 'Christoper@gmail.com', 'ROLE_USER', 'wmMzeMgr', 'wmMzeMgr', 70, '', 'Portugal', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Bill', '', 'Bill@ukr.net', 'ROLE_USER', 'yhXXxXOK', 'yhXXxXOK', 76, '', 'Congo', 'Male', 'London is a capital of Great Britain!', '', '', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Casimira', '', 'Casimira@mail.ru', 'ROLE_USER', 'kLUuvwpo', 'kLUuvwpo', 55, '', 'Kenya', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Xiomara', '', 'Xiomara@ukr.net', 'ROLE_USER', 'tqTwbPrw', 'tqTwbPrw', 113, '', 'Trinidad and Tobago', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Consuelo', '', 'Consuelo@gmail.com', 'ROLE_USER', 'cwqplUqb', 'cwqplUqb', 97, '', 'India', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Kelsi', '', 'Kelsi@rambler.ru', 'ROLE_USER', 'enXyVaKd', 'enXyVaKd', 93, '', 'Turkey', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Geraldine', '', 'Geraldine@rambler.ru', 'ROLE_USER', 'hkyvlRXx', 'hkyvlRXx', 65, '', 'Sint Maarten (Dutch part)', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Trista', '', 'Trista@gmail.com', 'ROLE_USER', 'gzVjMKrY', 'gzVjMKrY', 72, '', 'Togo', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');

INSERT INTO native_language (id, name, user_id) VALUES (1, 'Bengali', 3);
INSERT INTO native_language (id, name, user_id) VALUES (2, 'Portuguese (Portugal)', 3);
INSERT INTO native_language (id, name, user_id) VALUES (3, 'Basque', 3);
INSERT INTO native_language (id, name, user_id) VALUES (4, 'Norwegian', 3);
INSERT INTO native_language (id, name, user_id) VALUES (5, 'Maltese', 3);
INSERT INTO native_language (id, name, user_id) VALUES (6, 'Udmurt', 4);
INSERT INTO native_language (id, name, user_id) VALUES (7, 'Urdu', 4);
INSERT INTO native_language (id, name, user_id) VALUES (8, 'Flemish', 4);
INSERT INTO native_language (id, name, user_id) VALUES (9, 'Thai', 5);
INSERT INTO native_language (id, name, user_id) VALUES (10, 'Bulgarian', 5);
INSERT INTO native_language (id, name, user_id) VALUES (11, 'Ossetic', 5);
INSERT INTO native_language (id, name, user_id) VALUES (12, 'Arabic', 5);
INSERT INTO native_language (id, name, user_id) VALUES (13, 'Sinhalese', 6);
INSERT INTO native_language (id, name, user_id) VALUES (14, 'Lithuanian', 6);
INSERT INTO native_language (id, name, user_id) VALUES (15, 'Javanese', 6);
INSERT INTO native_language (id, name, user_id) VALUES (16, 'Portuguese (Brazil)', 6);
INSERT INTO native_language (id, name, user_id) VALUES (17, 'Georgian', 6);
INSERT INTO native_language (id, name, user_id) VALUES (18, 'Korean', 6);
INSERT INTO native_language (id, name, user_id) VALUES (19, 'Kirghiz', 7);
INSERT INTO native_language (id, name, user_id) VALUES (20, 'Khmer', 7);
INSERT INTO native_language (id, name, user_id) VALUES (21, 'Serbian', 7);
INSERT INTO native_language (id, name, user_id) VALUES (22, 'English', 7);
INSERT INTO native_language (id, name, user_id) VALUES (23, 'Italian', 7);
INSERT INTO native_language (id, name, user_id) VALUES (24, 'Maltese', 8);
INSERT INTO native_language (id, name, user_id) VALUES (25, 'Laotian', 8);
INSERT INTO native_language (id, name, user_id) VALUES (26, 'Ainu', 8);
INSERT INTO native_language (id, name, user_id) VALUES (27, 'German', 9);
INSERT INTO native_language (id, name, user_id) VALUES (28, 'Kirghiz', 9);
INSERT INTO native_language (id, name, user_id) VALUES (29, 'Afrikans', 9);
INSERT INTO native_language (id, name, user_id) VALUES (30, 'Swahili', 9);
INSERT INTO native_language (id, name, user_id) VALUES (31, 'Zulu', 9);
INSERT INTO native_language (id, name, user_id) VALUES (32, 'Georgian', 9);
INSERT INTO native_language (id, name, user_id) VALUES (33, 'Thai', 10);
INSERT INTO native_language (id, name, user_id) VALUES (34, 'Ainu', 10);
INSERT INTO native_language (id, name, user_id) VALUES (35, 'Javanese', 10);
INSERT INTO native_language (id, name, user_id) VALUES (36, 'Bihari', 10);
INSERT INTO native_language (id, name, user_id) VALUES (37, 'Irish', 10);
INSERT INTO native_language (id, name, user_id) VALUES (38, 'Bihari', 11);
INSERT INTO native_language (id, name, user_id) VALUES (39, 'Slavic', 11);
INSERT INTO native_language (id, name, user_id) VALUES (40, 'Romanian', 11);
INSERT INTO native_language (id, name, user_id) VALUES (41, 'Japanese', 11);
INSERT INTO native_language (id, name, user_id) VALUES (42, 'Welsh', 12);
INSERT INTO native_language (id, name, user_id) VALUES (43, 'Irish', 12);
INSERT INTO native_language (id, name, user_id) VALUES (44, 'Dutch', 12);
INSERT INTO native_language (id, name, user_id) VALUES (45, 'Esperanto', 12);
INSERT INTO native_language (id, name, user_id) VALUES (46, 'Armenian', 12);

INSERT INTO practicing_language (id, name, user_id) VALUES (1, 'Spanish', 3);
INSERT INTO practicing_language (id, name, user_id) VALUES (2, 'Ossetic', 3);
INSERT INTO practicing_language (id, name, user_id) VALUES (3, 'Mandarin', 4);
INSERT INTO practicing_language (id, name, user_id) VALUES (4, 'Dutch', 4);
INSERT INTO practicing_language (id, name, user_id) VALUES (5, 'Tongan', 4);
INSERT INTO practicing_language (id, name, user_id) VALUES (6, 'Dutch', 5);
INSERT INTO practicing_language (id, name, user_id) VALUES (7, 'Irish', 5);
INSERT INTO practicing_language (id, name, user_id) VALUES (8, 'German', 5);
INSERT INTO practicing_language (id, name, user_id) VALUES (9, 'Pashto', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (10, 'Flemish', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (11, 'Mandarin', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (12, 'Hungarian', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (13, 'Romani', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (14, 'Italian', 6);
INSERT INTO practicing_language (id, name, user_id) VALUES (15, 'Dutch', 7);
INSERT INTO practicing_language (id, name, user_id) VALUES (16, 'Javanese', 7);
INSERT INTO practicing_language (id, name, user_id) VALUES (17, 'Udmurt', 7);
INSERT INTO practicing_language (id, name, user_id) VALUES (18, 'Uyghur', 8);
INSERT INTO practicing_language (id, name, user_id) VALUES (19, 'English', 8);
INSERT INTO practicing_language (id, name, user_id) VALUES (20, 'Polish', 9);
INSERT INTO practicing_language (id, name, user_id) VALUES (21, 'Hawaiian', 9);
INSERT INTO practicing_language (id, name, user_id) VALUES (22, 'Telugu', 10);
INSERT INTO practicing_language (id, name, user_id) VALUES (23, 'Tagalog', 10);
INSERT INTO practicing_language (id, name, user_id) VALUES (24, 'Haitian', 10);
INSERT INTO practicing_language (id, name, user_id) VALUES (25, 'Georgian', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (26, 'Spanish', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (27, 'Basque', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (28, 'Haitian', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (29, 'Hawaiian', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (30, 'Armenian', 11);
INSERT INTO practicing_language (id, name, user_id) VALUES (31, 'Slovenian', 12);
INSERT INTO practicing_language (id, name, user_id) VALUES (32, 'Irish', 12);
INSERT INTO practicing_language (id, name, user_id) VALUES (33, 'Bosnian', 12);
INSERT INTO practicing_language (id, name, user_id) VALUES (34, 'Udmurt', 12);
