INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eugene', '', 'admin@gmail.com', 'ROLE_ADMIN', 'qwerty', 'qwerty', 23, '', 'Ukraine', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/profile.php?id=100001797104519', '', '', 'https://vk.com/zheki4', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Eugene', '', 'user@gmail.com', 'ROLE_USER', 'qwerty', 'qwerty', 23, '', 'Ukraine', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/profile.php?id=100001797104519', '', '', 'https://vk.com/zheki4', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Casimira', '', 'Casimira@mail.ru', 'ROLE_USER', 'PpyTtKdz', 'PpyTtKdz', 93, '', 'Equatorial Guinea', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Mitzi', '', 'Mitzi@mail.ru', 'ROLE_USER', 'ViStMZcf', 'ViStMZcf', 10, '', 'Norway', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Verla', '', 'Verla@gmail.com', 'ROLE_USER', 'llNvLWkX', 'llNvLWkX', 37, '', 'Tokelau', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marin', '', 'Marin@gmail.com', 'ROLE_USER', 'gRPZZSkV', 'gRPZZSkV', 35, '', 'Tonga', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Raquel', '', 'Raquel@rambler.ru', 'ROLE_USER', 'puozXajy', 'puozXajy', 98, '', 'Somalia', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Ivan', '', 'Ivan@gmail.com', 'ROLE_USER', 'TjLqkprN', 'TjLqkprN', 100, '', 'Gibraltar', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Mellie', '', 'Mellie@ukr.net', 'ROLE_USER', 'NVrfbxKm', 'NVrfbxKm', 97, '', 'Heard Island And McDonald Islands', 'Female', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Chung', '', 'Chung@ukr.net', 'ROLE_USER', 'XusshrQe', 'XusshrQe', 30, '', 'Morocco', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Joslyn', '', 'Joslyn@ukr.net', 'ROLE_USER', 'JQRZcVPu', 'JQRZcVPu', 55, '', 'Argentina', 'Female', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Chadwick', '', 'Chadwick@rambler.ru', 'ROLE_USER', 'frzPOVnK', 'frzPOVnK', 48, '', 'Saint Martin', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Sherlene', '', 'Sherlene@ukr.net', 'ROLE_USER', 'oKTuxXxK', 'oKTuxXxK', 16, '', 'Guam', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Darwin', '', 'Darwin@ukr.net', 'ROLE_USER', 'gVWWiOjX', 'gVWWiOjX', 88, '', 'Algeria', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Celestina', '', 'Celestina@gmail.com', 'ROLE_USER', 'gZpMObzn', 'gZpMObzn', 32, '', 'Japan', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Katherina', '', 'Katherina@rambler.ru', 'ROLE_USER', 'RaJaNNwQ', 'RaJaNNwQ', 86, '', 'Philippines', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Kasie', '', 'Kasie@ukr.net', 'ROLE_USER', 'tZpqzLiQ', 'tZpqzLiQ', 105, '', 'Slovenia', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Darwin', '', 'Darwin@gmail.com', 'ROLE_USER', 'QkKLUclV', 'QkKLUclV', 82, '', 'Reunion', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Oscar', '', 'Oscar@mail.ru', 'ROLE_USER', 'LjJwwXla', 'LjJwwXla', 73, '', 'Bouvet Island', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Shawn', '', 'Shawn@gmail.com', 'ROLE_USER', 'gNSxLsMy', 'gNSxLsMy', 53, '', 'Guyana', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Joesph', '', 'Joesph@rambler.ru', 'ROLE_USER', 'ueJpYmUo', 'ueJpYmUo', 38, '', 'Sierra Leone', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Elijah', '', 'Elijah@rambler.ru', 'ROLE_USER', 'RQMJdkjk', 'RQMJdkjk', 25, '', 'Cayman Islands', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Candis', '', 'Candis@gmail.com', 'ROLE_USER', 'oSgYKLOu', 'oSgYKLOu', 12, '', 'Eritrea', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Geraldine', '', 'Geraldine@mail.ru', 'ROLE_USER', 'bLTvwmsn', 'bLTvwmsn', 111, '', 'Kazakhstan', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Antoinette', '', 'Antoinette@mail.ru', 'ROLE_USER', 'wwMqrJRl', 'wwMqrJRl', 54, '', 'Algeria', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Mellie', '', 'Mellie@gmail.com', 'ROLE_USER', 'TdrzlkPX', 'TdrzlkPX', 56, '', 'Antarctica', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marica', '', 'Marica@ukr.net', 'ROLE_USER', 'VzlmdXwz', 'VzlmdXwz', 117, '', 'Martinique', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marica', '', 'Marica@gmail.com', 'ROLE_USER', 'yJtbvVmd', 'yJtbvVmd', 48, '', 'Macao', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Graham', '', 'Graham@rambler.ru', 'ROLE_USER', 'hrivcket', 'hrivcket', 32, '', 'Guyana', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Antoinette', '', 'Antoinette@rambler.ru', 'ROLE_USER', 'ajidjTcW', 'ajidjTcW', 50, '', 'Venezuela', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Sherlene', '', 'Sherlene@rambler.ru', 'ROLE_USER', 'qkPiZXQo', 'qkPiZXQo', 98, '', 'Portugal', 'Female', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Celestine', '', 'Celestine@gmail.com', 'ROLE_USER', 'lQUfaWQV', 'lQUfaWQV', 58, '', 'Ghana', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Consuelo', '', 'Consuelo@ukr.net', 'ROLE_USER', 'ewOinJlb', 'ewOinJlb', 109, '', 'Lesotho', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Dominick', '', 'Dominick@rambler.ru', 'ROLE_USER', 'nMiQbqYK', 'nMiQbqYK', 73, '', 'South Africa', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Philip', '', 'Philip@gmail.com', 'ROLE_USER', 'TQiWKcTj', 'TQiWKcTj', 59, '', 'Liechtenstein', 'Male', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Brittny', '', 'Brittny@ukr.net', 'ROLE_USER', 'XsoJRfqZ', 'XsoJRfqZ', 76, '', 'Trinidad and Tobago', 'Female', 'London is a capital of Great Britain!', '', '', '', '', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Ervin', '', 'Ervin@mail.ru', 'ROLE_USER', 'NtTxLROM', 'NtTxLROM', 78, '', 'Mongolia', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marvin', '', 'Marvin@rambler.ru', 'ROLE_USER', 'btiMtcpa', 'btiMtcpa', 13, '', 'Egypt', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Liana', '', 'Liana@ukr.net', 'ROLE_USER', 'xytrJmpg', 'xytrJmpg', 51, '', 'Somalia', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Josue', '', 'Josue@ukr.net', 'ROLE_USER', 'pwoeMgbd', 'pwoeMgbd', 101, '', 'Burundi', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Miguel', '', 'Miguel@rambler.ru', 'ROLE_USER', 'anpfjbsn', 'anpfjbsn', 82, '', 'Switzerland', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', '', 'https://plus.google.com/', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Solange', '', 'Solange@gmail.com', 'ROLE_USER', 'rJTnNRgq', 'rJTnNRgq', 22, '', 'Burkina Faso', 'Female', 'London is a capital of Great Britain!', '', '', '', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Jacki', '', 'Jacki@rambler.ru', 'ROLE_USER', 'gzjrykZL', 'gzjrykZL', 48, '', 'Guernsey', 'Female', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://plus.google.com/', 'https://vk.com/', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Donnell', '', 'Donnell@gmail.com', 'ROLE_USER', 'psmXNblK', 'psmXNblK', 80, '', 'Latvia', 'Male', 'London is a capital of Great Britain!', 'https://www.facebook.com/', 'https://www.twitter.com/', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Beata', '', 'Beata@ukr.net', 'ROLE_USER', 'vQKQVvaR', 'vQKQVvaR', 44, '', 'Turks And Caicos Islands', 'Female', 'London is a capital of Great Britain!', '', '', '', '', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Marvin', '', 'Marvin@gmail.com', 'ROLE_USER', 'gPMpmSKr', 'gPMpmSKr', 55, '', 'French Polynesia', 'Male', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', 'https://plus.google.com/', '', 'https://plus.google.com/', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Isiahn', '', 'Isiahn@rambler.ru', 'ROLE_USER', 'hdUxPSQK', 'hdUxPSQK', 88, '', 'Azerbaijan', 'Male', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Paris', '', 'Paris@mail.ru', 'ROLE_USER', 'SONZftgg', 'SONZftgg', 109, '', 'Tanzania', 'Male', 'London is a capital of Great Britain!', '', '', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Clarinda', '', 'Clarinda@mail.ru', 'ROLE_USER', 'TJkpubxl', 'TJkpubxl', 112, '', 'Norway', 'Female', 'London is a capital of Great Britain!', '', 'https://www.twitter.com/', '', 'https://vk.com/', '', '');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Shawn', '', 'Shawn@ukr.net', 'ROLE_USER', 'igkmJnnW', 'igkmJnnW', 82, '', 'Brazil', 'Male', 'London is a capital of Great Britain!', '', '', '', 'https://vk.com/', '', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Raquel', '', 'Raquel@mail.ru', 'ROLE_USER', 'xXlZdyMX', 'xXlZdyMX', 76, '', 'French Guiana', 'Female', 'London is a capital of Great Britain!', '', '', '', '', 'https://plus.google.com/', 'https://www.instagram.com/');
INSERT INTO app_user (first_name, last_name, email, role, password, confirmed_password, age, city, country, gender, description, facebook_link, twitter_link, google_link, vkontakte_link, linkedIn_link, instagram_link) VALUES ('Xiomara', '', 'Xiomara@gmail.com', 'ROLE_USER', 'uULVyYtc', 'uULVyYtc', 88, '', 'Solomon Islands', 'Female', 'London is a capital of Great Britain!', '', '', 'https://plus.google.com/', '', '', '');

INSERT INTO native_language (name, user_id) VALUES ('Ukrainian', 1);
INSERT INTO native_language (name, user_id) VALUES ('Russian', 1);
INSERT INTO native_language (name, user_id) VALUES ('Ukrainian', 2);
INSERT INTO native_language (name, user_id) VALUES ('Russian', 2);
INSERT INTO native_language (name, user_id) VALUES ('Myanmar', 3);
INSERT INTO native_language (name, user_id) VALUES ('Polish', 3);
INSERT INTO native_language (name, user_id) VALUES ('Laotian', 3);
INSERT INTO native_language (name, user_id) VALUES ('Marathi', 3);
INSERT INTO native_language (name, user_id) VALUES ('Kannada', 3);
INSERT INTO native_language (name, user_id) VALUES ('Uzbek', 4);
INSERT INTO native_language (name, user_id) VALUES ('Javanese', 4);
INSERT INTO native_language (name, user_id) VALUES ('Irish', 4);
INSERT INTO native_language (name, user_id) VALUES ('Panjabi', 4);
INSERT INTO native_language (name, user_id) VALUES ('Bosnian', 5);
INSERT INTO native_language (name, user_id) VALUES ('Arabic', 5);
INSERT INTO native_language (name, user_id) VALUES ('Uzbek', 5);
INSERT INTO native_language (name, user_id) VALUES ('Hindi', 6);
INSERT INTO native_language (name, user_id) VALUES ('Italian', 6);
INSERT INTO native_language (name, user_id) VALUES ('Georgian', 6);
INSERT INTO native_language (name, user_id) VALUES ('Cantonese', 6);
INSERT INTO native_language (name, user_id) VALUES ('Estonian', 6);
INSERT INTO native_language (name, user_id) VALUES ('Marathi', 6);
INSERT INTO native_language (name, user_id) VALUES ('Slovak', 7);
INSERT INTO native_language (name, user_id) VALUES ('Maltese', 7);
INSERT INTO native_language (name, user_id) VALUES ('Cantonese', 7);
INSERT INTO native_language (name, user_id) VALUES ('Mandarin', 8);
INSERT INTO native_language (name, user_id) VALUES ('Bosnian', 8);
INSERT INTO native_language (name, user_id) VALUES ('Mongolian', 9);
INSERT INTO native_language (name, user_id) VALUES ('Korean', 9);
INSERT INTO native_language (name, user_id) VALUES ('Portuguese (Portugal)', 9);
INSERT INTO native_language (name, user_id) VALUES ('Slavic', 9);
INSERT INTO native_language (name, user_id) VALUES ('Dutch', 9);
INSERT INTO native_language (name, user_id) VALUES ('Maltese', 10);
INSERT INTO native_language (name, user_id) VALUES ('Javanese', 10);
INSERT INTO native_language (name, user_id) VALUES ('Indonesian', 10);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 10);
INSERT INTO native_language (name, user_id) VALUES ('Turkmen', 11);
INSERT INTO native_language (name, user_id) VALUES ('Gaelic', 11);
INSERT INTO native_language (name, user_id) VALUES ('Indonesian', 11);
INSERT INTO native_language (name, user_id) VALUES ('Bulgarian', 11);
INSERT INTO native_language (name, user_id) VALUES ('Javanese', 11);
INSERT INTO native_language (name, user_id) VALUES ('Sinhalese', 11);
INSERT INTO native_language (name, user_id) VALUES ('Tibetan', 12);
INSERT INTO native_language (name, user_id) VALUES ('Tongan', 12);
INSERT INTO native_language (name, user_id) VALUES ('Lithuanian', 12);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 12);
INSERT INTO native_language (name, user_id) VALUES ('Greek', 12);
INSERT INTO native_language (name, user_id) VALUES ('Kurdish', 12);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 13);
INSERT INTO native_language (name, user_id) VALUES ('Laotian', 13);
INSERT INTO native_language (name, user_id) VALUES ('Macedonian', 13);
INSERT INTO native_language (name, user_id) VALUES ('Portuguese (Brazil)', 14);
INSERT INTO native_language (name, user_id) VALUES ('Serbian', 14);
INSERT INTO native_language (name, user_id) VALUES ('Azerbaijanian', 14);
INSERT INTO native_language (name, user_id) VALUES ('Uzbek', 14);
INSERT INTO native_language (name, user_id) VALUES ('Tibetan', 14);
INSERT INTO native_language (name, user_id) VALUES ('Korean', 14);
INSERT INTO native_language (name, user_id) VALUES ('Catalan', 15);
INSERT INTO native_language (name, user_id) VALUES ('Turkish', 15);
INSERT INTO native_language (name, user_id) VALUES ('Hungarian', 15);
INSERT INTO native_language (name, user_id) VALUES ('Pashto', 16);
INSERT INTO native_language (name, user_id) VALUES ('Bosnian', 16);
INSERT INTO native_language (name, user_id) VALUES ('Greek', 16);
INSERT INTO native_language (name, user_id) VALUES ('Tongan', 16);
INSERT INTO native_language (name, user_id) VALUES ('Greek', 17);
INSERT INTO native_language (name, user_id) VALUES ('Breton', 17);
INSERT INTO native_language (name, user_id) VALUES ('Mandarin', 17);
INSERT INTO native_language (name, user_id) VALUES ('Gaelic', 18);
INSERT INTO native_language (name, user_id) VALUES ('Romani', 18);
INSERT INTO native_language (name, user_id) VALUES ('Lithuanian', 18);
INSERT INTO native_language (name, user_id) VALUES ('Uzbek', 18);
INSERT INTO native_language (name, user_id) VALUES ('Persian', 18);
INSERT INTO native_language (name, user_id) VALUES ('Hawaiian', 18);
INSERT INTO native_language (name, user_id) VALUES ('Javanese', 19);
INSERT INTO native_language (name, user_id) VALUES ('Slovak', 19);
INSERT INTO native_language (name, user_id) VALUES ('Portuguese (Portugal)', 20);
INSERT INTO native_language (name, user_id) VALUES ('Hungarian', 20);
INSERT INTO native_language (name, user_id) VALUES ('Spanish', 20);
INSERT INTO native_language (name, user_id) VALUES ('Romanian', 20);
INSERT INTO native_language (name, user_id) VALUES ('Marathi', 20);
INSERT INTO native_language (name, user_id) VALUES ('Slovak', 20);
INSERT INTO native_language (name, user_id) VALUES ('German', 21);
INSERT INTO native_language (name, user_id) VALUES ('Breton', 21);
INSERT INTO native_language (name, user_id) VALUES ('Kirghiz', 21);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 21);
INSERT INTO native_language (name, user_id) VALUES ('Estonian', 21);
INSERT INTO native_language (name, user_id) VALUES ('Portuguese (Brazil)', 22);
INSERT INTO native_language (name, user_id) VALUES ('Welsh', 22);
INSERT INTO native_language (name, user_id) VALUES ('Sanskrit', 22);
INSERT INTO native_language (name, user_id) VALUES ('Yiddish', 22);
INSERT INTO native_language (name, user_id) VALUES ('Turkmen', 22);
INSERT INTO native_language (name, user_id) VALUES ('Korean', 22);
INSERT INTO native_language (name, user_id) VALUES ('Flemish', 23);
INSERT INTO native_language (name, user_id) VALUES ('Marathi', 23);
INSERT INTO native_language (name, user_id) VALUES ('Afrikans', 23);
INSERT INTO native_language (name, user_id) VALUES ('Hawaiian', 23);
INSERT INTO native_language (name, user_id) VALUES ('Thai', 23);
INSERT INTO native_language (name, user_id) VALUES ('Irish', 24);
INSERT INTO native_language (name, user_id) VALUES ('Yiddish', 24);
INSERT INTO native_language (name, user_id) VALUES ('Icelandic', 25);
INSERT INTO native_language (name, user_id) VALUES ('Mongolian', 25);
INSERT INTO native_language (name, user_id) VALUES ('Esperanto', 26);
INSERT INTO native_language (name, user_id) VALUES ('Bosnian', 26);
INSERT INTO native_language (name, user_id) VALUES ('Estonian', 26);
INSERT INTO native_language (name, user_id) VALUES ('Georgian', 26);
INSERT INTO native_language (name, user_id) VALUES ('Myanmar', 26);
INSERT INTO native_language (name, user_id) VALUES ('Icelandic', 27);
INSERT INTO native_language (name, user_id) VALUES ('Sinhalese', 27);
INSERT INTO native_language (name, user_id) VALUES ('Kurdish', 27);
INSERT INTO native_language (name, user_id) VALUES ('Slavic', 27);
INSERT INTO native_language (name, user_id) VALUES ('Afrikans', 27);
INSERT INTO native_language (name, user_id) VALUES ('Haitian', 28);
INSERT INTO native_language (name, user_id) VALUES ('Afrikans', 28);
INSERT INTO native_language (name, user_id) VALUES ('Basque', 29);
INSERT INTO native_language (name, user_id) VALUES ('Tongan', 29);
INSERT INTO native_language (name, user_id) VALUES ('Mandarin', 30);
INSERT INTO native_language (name, user_id) VALUES ('Armenian', 30);
INSERT INTO native_language (name, user_id) VALUES ('Haitian', 31);
INSERT INTO native_language (name, user_id) VALUES ('Navajo', 31);
INSERT INTO native_language (name, user_id) VALUES ('Ainu', 31);
INSERT INTO native_language (name, user_id) VALUES ('Sanskrit', 31);
INSERT INTO native_language (name, user_id) VALUES ('Telugu', 32);
INSERT INTO native_language (name, user_id) VALUES ('Burmese', 32);
INSERT INTO native_language (name, user_id) VALUES ('Hebrew', 32);
INSERT INTO native_language (name, user_id) VALUES ('Serbian', 32);
INSERT INTO native_language (name, user_id) VALUES ('Swedish', 33);
INSERT INTO native_language (name, user_id) VALUES ('Estonian', 33);
INSERT INTO native_language (name, user_id) VALUES ('Arabic', 34);
INSERT INTO native_language (name, user_id) VALUES ('Lojban', 34);
INSERT INTO native_language (name, user_id) VALUES ('Maltese', 35);
INSERT INTO native_language (name, user_id) VALUES ('Dutch', 35);
INSERT INTO native_language (name, user_id) VALUES ('Sinhalese', 35);
INSERT INTO native_language (name, user_id) VALUES ('Croatian', 35);
INSERT INTO native_language (name, user_id) VALUES ('Georgian', 35);
INSERT INTO native_language (name, user_id) VALUES ('Esperanto', 35);
INSERT INTO native_language (name, user_id) VALUES ('Mongolian', 36);
INSERT INTO native_language (name, user_id) VALUES ('Bihari', 36);
INSERT INTO native_language (name, user_id) VALUES ('Albanian', 36);
INSERT INTO native_language (name, user_id) VALUES ('Finnish', 37);
INSERT INTO native_language (name, user_id) VALUES ('Lojban', 37);
INSERT INTO native_language (name, user_id) VALUES ('Romani', 38);
INSERT INTO native_language (name, user_id) VALUES ('Albanian', 38);
INSERT INTO native_language (name, user_id) VALUES ('German', 38);
INSERT INTO native_language (name, user_id) VALUES ('Faroese', 38);
INSERT INTO native_language (name, user_id) VALUES ('Turkmen', 38);
INSERT INTO native_language (name, user_id) VALUES ('Khmer', 39);
INSERT INTO native_language (name, user_id) VALUES ('Tibetan', 39);
INSERT INTO native_language (name, user_id) VALUES ('Latvian', 39);
INSERT INTO native_language (name, user_id) VALUES ('Malay', 39);
INSERT INTO native_language (name, user_id) VALUES ('Marathi', 39);
INSERT INTO native_language (name, user_id) VALUES ('Kurdish', 39);
INSERT INTO native_language (name, user_id) VALUES ('Italian', 40);
INSERT INTO native_language (name, user_id) VALUES ('Uyghur', 40);
INSERT INTO native_language (name, user_id) VALUES ('Norwegian', 40);
INSERT INTO native_language (name, user_id) VALUES ('Sanskrit', 40);
INSERT INTO native_language (name, user_id) VALUES ('Slavic', 41);
INSERT INTO native_language (name, user_id) VALUES ('Tagalog', 41);
INSERT INTO native_language (name, user_id) VALUES ('Azerbaijanian', 42);
INSERT INTO native_language (name, user_id) VALUES ('Lithuanian', 42);
INSERT INTO native_language (name, user_id) VALUES ('Romani', 42);
INSERT INTO native_language (name, user_id) VALUES ('Telugu', 42);
INSERT INTO native_language (name, user_id) VALUES ('Japanese', 42);
INSERT INTO native_language (name, user_id) VALUES ('Korean', 42);
INSERT INTO native_language (name, user_id) VALUES ('Afrikans', 43);
INSERT INTO native_language (name, user_id) VALUES ('Korean', 43);
INSERT INTO native_language (name, user_id) VALUES ('Norwegian', 43);
INSERT INTO native_language (name, user_id) VALUES ('Udmurt', 43);
INSERT INTO native_language (name, user_id) VALUES ('Persian', 44);
INSERT INTO native_language (name, user_id) VALUES ('Albanian', 44);
INSERT INTO native_language (name, user_id) VALUES ('English', 44);
INSERT INTO native_language (name, user_id) VALUES ('Malay', 45);
INSERT INTO native_language (name, user_id) VALUES ('Indonesian', 45);
INSERT INTO native_language (name, user_id) VALUES ('Bulgarian', 45);
INSERT INTO native_language (name, user_id) VALUES ('Laotian', 45);
INSERT INTO native_language (name, user_id) VALUES ('Kannada', 45);
INSERT INTO native_language (name, user_id) VALUES ('Japanese', 45);
INSERT INTO native_language (name, user_id) VALUES ('Swahili', 46);
INSERT INTO native_language (name, user_id) VALUES ('Mandarin', 46);
INSERT INTO native_language (name, user_id) VALUES ('Hebrew', 46);
INSERT INTO native_language (name, user_id) VALUES ('Romanian', 47);
INSERT INTO native_language (name, user_id) VALUES ('Sinhalese', 47);
INSERT INTO native_language (name, user_id) VALUES ('Welsh', 47);
INSERT INTO native_language (name, user_id) VALUES ('Spanish', 47);
INSERT INTO native_language (name, user_id) VALUES ('Kirghiz', 47);
INSERT INTO native_language (name, user_id) VALUES ('Finnish', 47);
INSERT INTO native_language (name, user_id) VALUES ('Japanese', 48);
INSERT INTO native_language (name, user_id) VALUES ('Slovak', 48);
INSERT INTO native_language (name, user_id) VALUES ('Flemish', 48);
INSERT INTO native_language (name, user_id) VALUES ('Sanskrit', 48);
INSERT INTO native_language (name, user_id) VALUES ('Slavic', 48);
INSERT INTO native_language (name, user_id) VALUES ('Hebrew', 48);
INSERT INTO native_language (name, user_id) VALUES ('Telugu', 49);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 49);
INSERT INTO native_language (name, user_id) VALUES ('Japanese', 50);
INSERT INTO native_language (name, user_id) VALUES ('Sinhalese', 50);
INSERT INTO native_language (name, user_id) VALUES ('Italian', 51);
INSERT INTO native_language (name, user_id) VALUES ('Haitian', 51);
INSERT INTO native_language (name, user_id) VALUES ('Turkish', 51);
INSERT INTO native_language (name, user_id) VALUES ('Spanish', 51);
INSERT INTO native_language (name, user_id) VALUES ('Khmer', 51);
INSERT INTO native_language (name, user_id) VALUES ('Portuguese (Portugal)', 52);
INSERT INTO native_language (name, user_id) VALUES ('Bengali', 52);

INSERT INTO practicing_language (name, user_id) VALUES ('English', 1);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 1);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 2);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 2);
INSERT INTO practicing_language (name, user_id) VALUES ('Azerbaijanian', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Bulgarian', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Icelandic', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Croatian', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Maltese', 3);
INSERT INTO practicing_language (name, user_id) VALUES ('Greek', 4);
INSERT INTO practicing_language (name, user_id) VALUES ('Kirghiz', 4);
INSERT INTO practicing_language (name, user_id) VALUES ('Breton', 4);
INSERT INTO practicing_language (name, user_id) VALUES ('Tamil', 4);
INSERT INTO practicing_language (name, user_id) VALUES ('Hungarian', 4);
INSERT INTO practicing_language (name, user_id) VALUES ('Hebrew', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Swahili', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Dutch', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Persian', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Sinhalese', 5);
INSERT INTO practicing_language (name, user_id) VALUES ('Albanian', 6);
INSERT INTO practicing_language (name, user_id) VALUES ('Bihari', 6);
INSERT INTO practicing_language (name, user_id) VALUES ('Danish', 7);
INSERT INTO practicing_language (name, user_id) VALUES ('Persian', 7);
INSERT INTO practicing_language (name, user_id) VALUES ('Irish', 8);
INSERT INTO practicing_language (name, user_id) VALUES ('Sinhalese', 8);
INSERT INTO practicing_language (name, user_id) VALUES ('Dutch', 8);
INSERT INTO practicing_language (name, user_id) VALUES ('Swedish', 8);
INSERT INTO practicing_language (name, user_id) VALUES ('Uzbek', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Sanskrit', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Romanian', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Panjabi', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Latvian', 9);
INSERT INTO practicing_language (name, user_id) VALUES ('Slavic', 10);
INSERT INTO practicing_language (name, user_id) VALUES ('Telugu', 10);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 10);
INSERT INTO practicing_language (name, user_id) VALUES ('Tongan', 10);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkish', 11);
INSERT INTO practicing_language (name, user_id) VALUES ('Persian', 11);
INSERT INTO practicing_language (name, user_id) VALUES ('Ukrainian', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('Arabic', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('Swahili', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('German', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('Thai', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('Kirghiz', 12);
INSERT INTO practicing_language (name, user_id) VALUES ('Portuguese (Brazil)', 13);
INSERT INTO practicing_language (name, user_id) VALUES ('Estonian', 13);
INSERT INTO practicing_language (name, user_id) VALUES ('Faroese', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Esperanto', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Swedish', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Italian', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Cantonese', 14);
INSERT INTO practicing_language (name, user_id) VALUES ('Panjabi', 15);
INSERT INTO practicing_language (name, user_id) VALUES ('Yiddish', 15);
INSERT INTO practicing_language (name, user_id) VALUES ('Persian', 16);
INSERT INTO practicing_language (name, user_id) VALUES ('Uzbek', 16);
INSERT INTO practicing_language (name, user_id) VALUES ('Tibetan', 16);
INSERT INTO practicing_language (name, user_id) VALUES ('Sinhalese', 16);
INSERT INTO practicing_language (name, user_id) VALUES ('Bengali', 17);
INSERT INTO practicing_language (name, user_id) VALUES ('Pashto', 17);
INSERT INTO practicing_language (name, user_id) VALUES ('Welsh', 17);
INSERT INTO practicing_language (name, user_id) VALUES ('Bosnian', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('Norwegian', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('German', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('Portuguese (Portugal)', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('Malay', 18);
INSERT INTO practicing_language (name, user_id) VALUES ('Swahili', 19);
INSERT INTO practicing_language (name, user_id) VALUES ('Serbian', 19);
INSERT INTO practicing_language (name, user_id) VALUES ('Lithuanian', 20);
INSERT INTO practicing_language (name, user_id) VALUES ('Icelandic', 20);
INSERT INTO practicing_language (name, user_id) VALUES ('Urdu', 21);
INSERT INTO practicing_language (name, user_id) VALUES ('Croatian', 21);
INSERT INTO practicing_language (name, user_id) VALUES ('Italian', 21);
INSERT INTO practicing_language (name, user_id) VALUES ('Icelandic', 22);
INSERT INTO practicing_language (name, user_id) VALUES ('Laotian', 22);
INSERT INTO practicing_language (name, user_id) VALUES ('Romani', 23);
INSERT INTO practicing_language (name, user_id) VALUES ('Kannada', 23);
INSERT INTO practicing_language (name, user_id) VALUES ('Tamil', 23);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 23);
INSERT INTO practicing_language (name, user_id) VALUES ('Ukrainian', 23);
INSERT INTO practicing_language (name, user_id) VALUES ('Tagalog', 24);
INSERT INTO practicing_language (name, user_id) VALUES ('Slavic', 24);
INSERT INTO practicing_language (name, user_id) VALUES ('Hawaiian', 24);
INSERT INTO practicing_language (name, user_id) VALUES ('Polish', 24);
INSERT INTO practicing_language (name, user_id) VALUES ('Breton', 25);
INSERT INTO practicing_language (name, user_id) VALUES ('Mandarin', 25);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 25);
INSERT INTO practicing_language (name, user_id) VALUES ('German', 25);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkmen', 26);
INSERT INTO practicing_language (name, user_id) VALUES ('Arabic', 26);
INSERT INTO practicing_language (name, user_id) VALUES ('Myanmar', 26);
INSERT INTO practicing_language (name, user_id) VALUES ('Norwegian', 26);
INSERT INTO practicing_language (name, user_id) VALUES ('Cantonese', 26);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 27);
INSERT INTO practicing_language (name, user_id) VALUES ('Korean', 27);
INSERT INTO practicing_language (name, user_id) VALUES ('Tamil', 27);
INSERT INTO practicing_language (name, user_id) VALUES ('Basque', 27);
INSERT INTO practicing_language (name, user_id) VALUES ('Bulgarian', 28);
INSERT INTO practicing_language (name, user_id) VALUES ('Kannada', 28);
INSERT INTO practicing_language (name, user_id) VALUES ('Afrikans', 28);
INSERT INTO practicing_language (name, user_id) VALUES ('Chinese Traditional', 28);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 28);
INSERT INTO practicing_language (name, user_id) VALUES ('Swahili', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Laotian', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Serbian', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Azerbaijanian', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Navajo', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 29);
INSERT INTO practicing_language (name, user_id) VALUES ('Slavic', 30);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 30);
INSERT INTO practicing_language (name, user_id) VALUES ('Welsh', 30);
INSERT INTO practicing_language (name, user_id) VALUES ('Gaelic', 30);
INSERT INTO practicing_language (name, user_id) VALUES ('Azerbaijanian', 30);
INSERT INTO practicing_language (name, user_id) VALUES ('Slovenian', 31);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkmen', 31);
INSERT INTO practicing_language (name, user_id) VALUES ('Polish', 31);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 32);
INSERT INTO practicing_language (name, user_id) VALUES ('Greek', 32);
INSERT INTO practicing_language (name, user_id) VALUES ('Yiddish', 33);
INSERT INTO practicing_language (name, user_id) VALUES ('Flemish', 33);
INSERT INTO practicing_language (name, user_id) VALUES ('Telugu', 33);
INSERT INTO practicing_language (name, user_id) VALUES ('Esperanto', 33);
INSERT INTO practicing_language (name, user_id) VALUES ('Portuguese (Portugal)', 34);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 34);
INSERT INTO practicing_language (name, user_id) VALUES ('Hebrew', 34);
INSERT INTO practicing_language (name, user_id) VALUES ('Faroese', 34);
INSERT INTO practicing_language (name, user_id) VALUES ('Azerbaijanian', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Serbian', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Cantonese', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkmen', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Polish', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Navajo', 35);
INSERT INTO practicing_language (name, user_id) VALUES ('Icelandic', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Portuguese (Portugal)', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Czech', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Welsh', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Marathi', 36);
INSERT INTO practicing_language (name, user_id) VALUES ('Latvian', 37);
INSERT INTO practicing_language (name, user_id) VALUES ('Albanian', 37);
INSERT INTO practicing_language (name, user_id) VALUES ('Zulu', 37);
INSERT INTO practicing_language (name, user_id) VALUES ('Norwegian', 38);
INSERT INTO practicing_language (name, user_id) VALUES ('Ukrainian', 38);
INSERT INTO practicing_language (name, user_id) VALUES ('Italian', 38);
INSERT INTO practicing_language (name, user_id) VALUES ('Javanese', 39);
INSERT INTO practicing_language (name, user_id) VALUES ('Irish', 39);
INSERT INTO practicing_language (name, user_id) VALUES ('Uyghur', 39);
INSERT INTO practicing_language (name, user_id) VALUES ('Portuguese (Portugal)', 39);
INSERT INTO practicing_language (name, user_id) VALUES ('Bosnian', 39);
INSERT INTO practicing_language (name, user_id) VALUES ('Basque', 40);
INSERT INTO practicing_language (name, user_id) VALUES ('Chinese Traditional', 40);
INSERT INTO practicing_language (name, user_id) VALUES ('Albanian', 40);
INSERT INTO practicing_language (name, user_id) VALUES ('Uyghur', 40);
INSERT INTO practicing_language (name, user_id) VALUES ('Macedonian', 40);
INSERT INTO practicing_language (name, user_id) VALUES ('Basque', 41);
INSERT INTO practicing_language (name, user_id) VALUES ('Ukrainian', 41);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 41);
INSERT INTO practicing_language (name, user_id) VALUES ('Swahili', 41);
INSERT INTO practicing_language (name, user_id) VALUES ('Panjabi', 41);
INSERT INTO practicing_language (name, user_id) VALUES ('Chinese Traditional', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkish', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('Slovenian', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('Khmer', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('Burmese', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('English', 42);
INSERT INTO practicing_language (name, user_id) VALUES ('Bulgarian', 43);
INSERT INTO practicing_language (name, user_id) VALUES ('Spanish', 43);
INSERT INTO practicing_language (name, user_id) VALUES ('Danish', 43);
INSERT INTO practicing_language (name, user_id) VALUES ('Sanskrit', 43);
INSERT INTO practicing_language (name, user_id) VALUES ('Lithuanian', 44);
INSERT INTO practicing_language (name, user_id) VALUES ('Tagalog', 44);
INSERT INTO practicing_language (name, user_id) VALUES ('Udmurt', 44);
INSERT INTO practicing_language (name, user_id) VALUES ('Afrikans', 44);
INSERT INTO practicing_language (name, user_id) VALUES ('Chinese Traditional', 44);
INSERT INTO practicing_language (name, user_id) VALUES ('Estonian', 45);
INSERT INTO practicing_language (name, user_id) VALUES ('Gaelic', 45);
INSERT INTO practicing_language (name, user_id) VALUES ('Latin', 45);
INSERT INTO practicing_language (name, user_id) VALUES ('Arabic', 45);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkish', 46);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkmen', 46);
INSERT INTO practicing_language (name, user_id) VALUES ('Malay', 46);
INSERT INTO practicing_language (name, user_id) VALUES ('Tibetan', 47);
INSERT INTO practicing_language (name, user_id) VALUES ('Welsh', 47);
INSERT INTO practicing_language (name, user_id) VALUES ('Hebrew', 47);
INSERT INTO practicing_language (name, user_id) VALUES ('Slovenian', 47);
INSERT INTO practicing_language (name, user_id) VALUES ('Polish', 47);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkish', 48);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 48);
INSERT INTO practicing_language (name, user_id) VALUES ('German', 48);
INSERT INTO practicing_language (name, user_id) VALUES ('Uyghur', 48);
INSERT INTO practicing_language (name, user_id) VALUES ('Lojban', 49);
INSERT INTO practicing_language (name, user_id) VALUES ('Turkish', 49);
INSERT INTO practicing_language (name, user_id) VALUES ('Zulu', 49);
INSERT INTO practicing_language (name, user_id) VALUES ('Esperanto', 49);
INSERT INTO practicing_language (name, user_id) VALUES ('Estonian', 50);
INSERT INTO practicing_language (name, user_id) VALUES ('Ainu', 50);
INSERT INTO practicing_language (name, user_id) VALUES ('Croatian', 51);
INSERT INTO practicing_language (name, user_id) VALUES ('Bihari', 51);
INSERT INTO practicing_language (name, user_id) VALUES ('Albanian', 51);
INSERT INTO practicing_language (name, user_id) VALUES ('Khmer', 52);
INSERT INTO practicing_language (name, user_id) VALUES ('Haitian', 52);